openapi: 3.0.3
info:
  title: 'Blog documentation'
  description: 'log documentation'
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/login:
    post:
      summary: 'Login user'
      operationId: loginUser
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Auth management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: awyman@example.org
                password:
                  type: string
                  description: ''
                  example: aliquam
              required:
                - email
                - password
      security: []
  /api/logout:
    post:
      summary: 'Logout user'
      operationId: logoutUser
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Auth management'
  /api/categories:
    get:
      summary: 'List categories'
      operationId: listCategories
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'Category management'
    post:
      summary: 'Create categories'
      operationId: createCategories
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Category management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: est
              required:
                - name
  '/api/categories/{id}':
    get:
      summary: 'Show categories'
      operationId: showCategories
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'Category management'
    delete:
      summary: 'Delete categories'
      operationId: deleteCategories
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Category management'
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the category.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/comments/{type}/{typeId}':
    get:
      summary: 'List comments for morphic model'
      operationId: listCommentsForMorphicModel
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'Comment management'
    post:
      summary: 'Create comments for morphic model'
      operationId: createCommentsForMorphicModel
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Comment management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                  description: ''
                  example: libero
              required:
                - body
    parameters:
      -
        in: path
        name: type
        description: ''
        example: commodi
        required: true
        schema:
          type: string
      -
        in: path
        name: typeId
        description: ''
        example: molestiae
        required: true
        schema:
          type: string
  '/api/comments/{id}':
    put:
      summary: 'Update comment'
      operationId: updateComment
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Comment management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                  description: ''
                  example: libero
              required:
                - body
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the comment.'
        example: quidem
        required: true
        schema:
          type: string
  /api/posts:
    get:
      summary: 'List posts'
      operationId: listPosts
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'Post management'
    post:
      summary: 'Create post'
      operationId: createPost
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Post management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: hqihmlchgroxw
                body:
                  type: string
                  description: ''
                  example: mollitia
                category_id:
                  type: string
                  description: ''
                  example: necessitatibus
                tags:
                  type: object
                  description: ''
                  example: null
                  properties: {  }
              required:
                - title
                - body
                - category_id
  '/api/posts/{id}':
    get:
      summary: 'Show post'
      operationId: showPost
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'Post management'
    put:
      summary: 'Update post'
      operationId: updatePost
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Post management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: timnrsnvcu
                body:
                  type: string
                  description: ''
                  example: earum
                category_id:
                  type: string
                  description: ''
                  example: unde
                tags:
                  type: object
                  description: ''
                  example: null
                  properties: {  }
              required:
                - title
                - body
                - category_id
    delete:
      summary: 'Delete post'
      operationId: deletePost
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Post management'
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the post.'
        example: 1
        required: true
        schema:
          type: integer
  /api/users:
    get:
      summary: 'User list'
      operationId: userList
      description: 'Display a listing of the resource.'
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'User management'
    post:
      summary: 'Create User'
      operationId: createUser
      description: 'Store a newly created resource in storage.'
      parameters: []
      responses: {  }
      tags:
        - 'User management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: fbklbvsnevgsuyiyjdoyklkuo
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: jlehner@example.org
                password:
                  type: string
                  description: 'Must be at least 6 characters.'
                  example: '*-<Os*@s<.'
              required:
                - name
                - email
                - password
  '/api/users/{id}':
    get:
      summary: 'Show user'
      operationId: showUser
      description: 'Display the specified resource.'
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'User management'
    put:
      summary: 'Update user'
      operationId: updateUser
      description: 'Update the specified resource in storage.'
      parameters: []
      responses: {  }
      tags:
        - 'User management'
    delete:
      summary: 'Delete user'
      operationId: deleteUser
      description: 'Remove the specified resource from storage.'
      parameters: []
      responses: {  }
      tags:
        - 'User management'
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the user.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: 'Auth management'
    description: 'APIs for managing authentication'
  -
    name: 'Category management'
    description: 'APIs for managing categories'
  -
    name: 'Comment management'
    description: 'APIs for managing comments'
  -
    name: 'Post management'
    description: 'APIs for managing posts'
  -
    name: 'User management'
    description: 'APIs for managing users'
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
